[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"


[project]
name = "panagram"
version = "0.0.1"
dependencies = [
    "simple_parsing",
    "plotly",
    "dash",
    "pysam",
    "pandas",
    "Bio",
    "scipy",
    "toml",
    "bgzip",
    "mycolorpy",
]

[project.scripts]
panagram = "panagram.__main__:main"
